name: Pipeline Integration Test

on:
  push:
    tags:
      - '*'

jobs:
  run-pipelines:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Configure environment for geffen-pipelines
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        environment-file: geffen-pipelines.yml
        activate-environment: geffen-pipelines

    - name: Fetch Input Data
      shell: bash -el {0}
      run: |
        mkdir -p raw_data/CI
        mkdir -p processed_data/
        mkdir -p analysis/
        mkdir -p scratch/

        cd raw_data/CI/
        wget https://storage.googleapis.com/tripledip-geffenlab/AS20-minimal3.zip
        unzip AS20-minimal3.zip
        pwd
        ls -althR

    - name: Proceed pipeline
      shell: bash -el {0}
      run: |
        proceed run proceed/ci-nidq.yaml --args raw_data_root=$PWD/raw_data processed_data_root=$PWD/processed_data analysis_root=$PWD/analysis scratch_root=$PWD/scratch

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-logs-and-figures
        retention-days: 7
        path: |
          proceed_out/
          analysis/**/*.png
